import type { Visit } from '@/types/domain';
import { DEV_USER_ID } from '@/constants/features';

const daysAgo = (days: number, hours = 12, minutes = 0) => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  date.setHours(hours, minutes, 0, 0);
  return date.toISOString();
};

/** Sample visits shown when the user has no logged visits yet */
export const DEMO_VISITS: Visit[] = [
  {
    id: 'demo-1',
    userId: DEV_USER_ID,
    latitude: 28.5455,
    longitude: 77.1926,
    placeName: 'Cafe Tesu',
    address: 'Sri Aurobindo Marg, New Delhi',
    category: 'cafe',
    city: 'New Delhi',
    state: 'Delhi',
    country: 'India',
    arrivedAt: daysAgo(0, 9, 30),
    departedAt: daysAgo(0, 11, 0),
    durationMinutes: 90,
    createdAt: daysAgo(0, 11, 0),
  },
  {
    id: 'demo-2',
    userId: DEV_USER_ID,
    latitude: 28.6129,
    longitude: 77.2295,
    placeName: 'India Gate',
    address: 'Rajpath, New Delhi',
    category: 'park',
    city: 'New Delhi',
    state: 'Delhi',
    country: 'India',
    arrivedAt: daysAgo(1, 17, 0),
    departedAt: daysAgo(1, 18, 15),
    durationMinutes: 75,
    createdAt: daysAgo(1, 18, 15),
  },
  {
    id: 'demo-3',
    userId: DEV_USER_ID,
    latitude: 28.5535,
    longitude: 77.2588,
    placeName: 'Select Citywalk',
    address: 'Saket, New Delhi',
    category: 'mall',
    city: 'New Delhi',
    state: 'Delhi',
    country: 'India',
    arrivedAt: daysAgo(3, 14, 0),
    departedAt: daysAgo(3, 17, 30),
    durationMinutes: 210,
    createdAt: daysAgo(3, 17, 30),
  },
  {
    id: 'demo-4',
    userId: DEV_USER_ID,
    latitude: 28.5244,
    longitude: 77.1855,
    placeName: 'Blue Tokai Coffee',
    address: 'Vasant Kunj, New Delhi',
    category: 'cafe',
    city: 'New Delhi',
    state: 'Delhi',
    country: 'India',
    arrivedAt: daysAgo(5, 10, 0),
    departedAt: daysAgo(5, 11, 20),
    durationMinutes: 80,
    createdAt: daysAgo(5, 11, 20),
  },
  {
    id: 'demo-5',
    userId: DEV_USER_ID,
    latitude: 28.7041,
    longitude: 77.1025,
    placeName: 'Cyber Hub',
    address: 'Gurugram, Haryana',
    category: 'restaurant',
    city: 'Gurugram',
    state: 'Haryana',
    country: 'India',
    arrivedAt: daysAgo(8, 19, 30),
    departedAt: daysAgo(8, 22, 0),
    durationMinutes: 150,
    createdAt: daysAgo(8, 22, 0),
  },
  {
    id: 'demo-6',
    userId: DEV_USER_ID,
    latitude: 19.076,
    longitude: 72.8777,
    placeName: 'Colaba Causeway',
    address: 'Mumbai, Maharashtra',
    category: 'store',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    arrivedAt: daysAgo(14, 16, 0),
    departedAt: daysAgo(14, 18, 45),
    durationMinutes: 165,
    createdAt: daysAgo(14, 18, 45),
  },
];

export const CATEGORY_LABELS: Record<Visit['category'], string> = {
  restaurant: 'Restaurant',
  cafe: 'Café',
  gym: 'Gym',
  park: 'Park',
  mall: 'Shopping',
  office: 'Office',
  home: 'Home',
  school: 'School',
  hospital: 'Hospital',
  sports_facility: 'Sports',
  store: 'Store',
  other: 'Other',
};

export const CATEGORY_EMOJI: Record<Visit['category'], string> = {
  restaurant: '🍴',
  cafe: '☕',
  gym: '💪',
  park: '🌳',
  mall: '🛍️',
  office: '🏢',
  home: '🏠',
  school: '🎓',
  hospital: '🏥',
  sports_facility: '⚽',
  store: '🏪',
  other: '📍',
};
